# Generated by Django 5.2.8 on 2025-11-19 07:58

import django.db.models.deletion
import ort_ims.plans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TCheckouts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("checkout_date", models.DateField(verbose_name="领用日期")),
                (
                    "checkout_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="领用单号"
                    ),
                ),
                ("PartNo", models.CharField(max_length=15, verbose_name="机种名称")),
                ("checkout_qty", models.IntegerField(verbose_name="领出数量")),
                ("SN", models.TextField(blank=True, null=True, verbose_name="序列号")),
                ("DC", models.CharField(max_length=8, verbose_name="周期")),
                ("REV", models.CharField(max_length=10, verbose_name="版本")),
                (
                    "Work_Order",
                    models.CharField(max_length=40, unique=True, verbose_name="工令"),
                ),
                (
                    "Remarks",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "checkout_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "未领用"), (2, "已领用"), (3, "已归还")],
                        default=2,
                        null=True,
                        verbose_name="领出状态",
                    ),
                ),
                (
                    "sn_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ort_ims.plans.models.RenameFile("sn_files/"),
                        verbose_name="序列号文件",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TCustCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cust_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="客户代码"
                    ),
                ),
                ("cust_name", models.CharField(max_length=50, verbose_name="客户名称")),
            ],
        ),
        migrations.CreateModel(
            name="TProductType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="产品代码"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(max_length=20, verbose_name="产品类型"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TTechnician",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tech_code",
                    models.CharField(max_length=10, unique=True, verbose_name="工号"),
                ),
                ("tech_name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "tech_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "tech_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TTestItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "test_item",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="测试项目"
                    ),
                ),
                ("test_time", models.FloatField(verbose_name="测试时间(h)")),
                (
                    "test_owner",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="测试负责人"
                    ),
                ),
                (
                    "dispose",
                    models.CharField(
                        blank=True,
                        choices=[("回线", "回线"), ("报废", "报废")],
                        max_length=25,
                        null=True,
                        verbose_name="样品处理",
                    ),
                ),
                (
                    "Remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "JobNo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="工作编号"
                    ),
                ),
                (
                    "QRT",
                    models.BooleanField(
                        choices=[(False, "领用"), (True, "送测")],
                        default=False,
                        verbose_name="送测",
                    ),
                ),
                ("PartNo", models.CharField(max_length=15, verbose_name="机种名")),
                (
                    "Stage",
                    models.IntegerField(
                        choices=[(1, "MP"), (2, "MVT"), (3, "DVT"), (4, "EVT")],
                        default=1,
                        verbose_name="阶段",
                    ),
                ),
                ("SampleSize", models.IntegerField(default=3, verbose_name="样品数")),
                ("TestPeriod", models.IntegerField(verbose_name="试验时间")),
                (
                    "Owner",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="负责人"
                    ),
                ),
                ("StartDate", models.DateField(verbose_name="开始日期")),
                (
                    "EndDate",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "Status",
                    models.IntegerField(
                        choices=[(1, "Ongoing"), (2, "Close"), (3, "Pending")],
                        default=1,
                        verbose_name="完成状态",
                    ),
                ),
                (
                    "Upload_Elab",
                    models.BooleanField(
                        blank=True,
                        choices=[(False, "未上传"), (True, "已上传")],
                        default=False,
                        null=True,
                        verbose_name="上传系统",
                    ),
                ),
                (
                    "Work_Order",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="工令",
                    ),
                ),
                (
                    "Remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "Customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.tcustcode",
                        verbose_name="客户名称",
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.tproducttype",
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "TestItem",
                    models.ForeignKey(
                        blank=True,
                        default=29,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="plans.ttestitem",
                        verbose_name="测试项目",
                    ),
                ),
            ],
        ),
    ]
