# Generated by Django 5.2.8 on 2026-01-25 03:23

import django.db.models.deletion
import django.utils.timezone
import ort_ims.plans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("managements", "0004_alter_ttestitem_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCheckouts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("checkout_date", models.DateField(verbose_name="领用日期")),
                (
                    "checkout_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="领用单号"
                    ),
                ),
                ("partno", models.CharField(max_length=15, verbose_name="机种名称")),
                (
                    "checkout_qty",
                    models.IntegerField(default=3, verbose_name="领出数量"),
                ),
                ("sn", models.TextField(blank=True, default="", verbose_name="序列号")),
                ("dc", models.CharField(max_length=8, verbose_name="周期")),
                ("rev", models.CharField(max_length=10, verbose_name="版本")),
                (
                    "workorder",
                    models.CharField(max_length=40, unique=True, verbose_name="工令"),
                ),
                (
                    "rt_workorder",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="回线RT工令"
                    ),
                ),
                (
                    "return_no",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="退料单号"
                    ),
                ),
                ("return_qty", models.IntegerField(default=3, verbose_name="入库数量")),
                (
                    "return_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入库日期"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "未领用"), (2, "已领用"), (3, "已归还")],
                        default=2,
                        null=True,
                        verbose_name="单体状态",
                    ),
                ),
                (
                    "sn_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ort_ims.plans.models.RenameFile("sn_files/"),
                        verbose_name="序列号文件",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TSchedule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jobno",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="工作编号"
                    ),
                ),
                (
                    "QRT",
                    models.BooleanField(
                        choices=[(False, "领用"), (True, "送测")],
                        default=False,
                        verbose_name="送测",
                    ),
                ),
                ("partno", models.CharField(max_length=15, verbose_name="机种名")),
                (
                    "stage",
                    models.IntegerField(
                        choices=[(1, "MP"), (2, "MVT"), (3, "DVT"), (4, "EVT")],
                        default=1,
                        verbose_name="阶段",
                    ),
                ),
                ("qty", models.IntegerField(default=3, verbose_name="样品数")),
                ("test_period", models.IntegerField(verbose_name="试验时间")),
                (
                    "owner",
                    models.CharField(
                        default="NA", max_length=50, verbose_name="负责人"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Ongoing"), (2, "Close"), (3, "Pending")],
                        default=1,
                        verbose_name="完成状态",
                    ),
                ),
                (
                    "upload_elab",
                    models.BooleanField(
                        blank=True,
                        choices=[(False, "未上传"), (True, "已上传")],
                        default=False,
                        null=True,
                        verbose_name="上传系统",
                    ),
                ),
                (
                    "workorder",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="工令",
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="managements.tcustcode",
                        verbose_name="客户名称",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="managements.tproducttype",
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "test_item",
                    models.ForeignKey(
                        blank=True,
                        default=29,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="managements.ttestitem",
                        verbose_name="测试项目",
                    ),
                ),
            ],
        ),
    ]
