# Generated by Django 5.2.8 on 2025-11-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TTechnician",
        ),
    ]
