# Generated by Django 5.2.8 on 2025-11-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0002_tcustcode_tproducttype_ttestitem"),
        ("plans", "0002_delete_ttechnician"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tschedule",
            name="Customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="managements.tcustcode",
                verbose_name="客户名称",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="managements.tproducttype",
                verbose_name="产品类型",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="TestItem",
            field=models.ForeignKey(
                blank=True,
                default=29,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="managements.ttestitem",
                verbose_name="测试项目",
            ),
        ),
        migrations.DeleteModel(
            name="TCustCode",
        ),
        migrations.DeleteModel(
            name="TProductType",
        ),
        migrations.DeleteModel(
            name="TTestItem",
        ),
    ]
