# Generated by Django 5.2.8 on 2026-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_tschedule_customer_alter_tschedule_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcheckouts",
            name="Remarks",
            field=models.TextField(default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="SN",
            field=models.TextField(blank=True, default="", verbose_name="序列号"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Owner",
            field=models.CharField(default="NA", max_length=50, verbose_name="负责人"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Remark",
            field=models.TextField(default="", verbose_name="备注"),
        ),
    ]
