# Generated by Django 5.2.8 on 2026-01-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_alter_tcheckouts_remarks_alter_tcheckouts_sn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tcheckouts",
            name="Remarks",
        ),
        migrations.AddField(
            model_name="tcheckouts",
            name="Remark",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Remark",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
    ]
