# Generated by Django 5.2.8 on 2026-01-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_remove_tcheckouts_remarks_tcheckouts_remark_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcheckouts",
            name="checkout_qty",
            field=models.IntegerField(default=3, verbose_name="领出数量"),
        ),
    ]
