# Generated by Django 5.2.8 on 2026-01-14 07:19

import django.db.models.deletion
import ort_ims.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("managements", "0003_alter_ttechnician_tech_email_and_more"),
        ("plans", "0004_alter_tcheckouts_remarks_alter_tcheckouts_sn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TORTReportOverview",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("PartNo", models.CharField(max_length=15, verbose_name="机种名称")),
                ("dc", models.CharField(max_length=8, verbose_name="周期")),
                (
                    "overview_file",
                    models.FileField(
                        unique=True,
                        upload_to=ort_ims.reports.models.RenameFile("reports/"),
                        verbose_name="报告总览",
                    ),
                ),
                ("make_date", models.DateField(verbose_name="创建日期")),
                (
                    "JobNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.tschedule",
                        to_field="JobNo",
                        verbose_name="工作编号",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TORTReports",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("PartNo", models.CharField(max_length=15, verbose_name="机种名称")),
                ("dc", models.CharField(max_length=8, verbose_name="周期")),
                (
                    "report_file",
                    models.FileField(
                        unique=True,
                        upload_to=ort_ims.reports.models.RenameFile(
                            "reports/", "Report"
                        ),
                        verbose_name="报告文件",
                    ),
                ),
                ("make_date", models.DateField(verbose_name="创建日期")),
                ("close_date", models.DateField(verbose_name="完成日期")),
                ("Remarks", models.TextField(default="", verbose_name="备注")),
                (
                    "JobNo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.tschedule",
                        to_field="JobNo",
                        verbose_name="工作编号",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="managements.ttestitem",
                        to_field="test_item",
                        verbose_name="测试类型",
                    ),
                ),
            ],
        ),
    ]
