# Generated by Django 5.2.8 on 2026-01-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tortreports",
            old_name="Remarks",
            new_name="Remark",
        ),
    ]
