# Generated by Django 5.2.8 on 2025-11-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TTechnician",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tech_code",
                    models.CharField(max_length=10, unique=True, verbose_name="工号"),
                ),
                ("tech_name", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "tech_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "tech_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="电话"
                    ),
                ),
            ],
        ),
    ]
