# Generated by Django 5.2.8 on 2025-11-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TCustCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cust_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="客户代码"
                    ),
                ),
                ("cust_name", models.CharField(max_length=50, verbose_name="客户名称")),
            ],
        ),
        migrations.CreateModel(
            name="TProductType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="产品代码"
                    ),
                ),
                (
                    "product_type",
                    models.CharField(max_length=20, verbose_name="产品类型"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TTestItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "test_item",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="测试项目"
                    ),
                ),
                ("test_time", models.FloatField(verbose_name="测试时间(h)")),
                (
                    "test_owner",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="测试负责人"
                    ),
                ),
                (
                    "dispose",
                    models.CharField(
                        blank=True,
                        choices=[("回线", "回线"), ("报废", "报废")],
                        max_length=25,
                        null=True,
                        verbose_name="样品处理",
                    ),
                ),
                (
                    "Remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
        ),
    ]
