# Generated by Django 5.2.8 on 2026-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0002_tcustcode_tproducttype_ttestitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_email",
            field=models.EmailField(default="", max_length=254, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_phone",
            field=models.CharField(default="", max_length=20, verbose_name="电话"),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="Remark",
            field=models.TextField(default="", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="dispose",
            field=models.CharField(
                choices=[("回线", "回线"), ("报废", "报废")],
                default="回线",
                max_length=25,
                verbose_name="样品处理",
            ),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="test_owner",
            field=models.CharField(
                default="NA", max_length=50, verbose_name="测试负责人"
            ),
        ),
    ]
