# Generated by Django 5.2.8 on 2026-01-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managements", "0003_alter_ttechnician_tech_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ttestitem",
            name="Remark",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
    ]
